services:
  app:
    image: automatic_task_arranging:${VERSION:-latest}
    container_name: automatic_task_arranging-test
    restart: unless-stopped
    environment:
      - DISPLAY=:99
    volumes:
      - app_data:/app/data
    # We're using the CMD in the Dockerfile, so no need to override command here
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep '[R]uby' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  app_data: